version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Проброс портов: Первый номер - порт на вашей локальной машине, второй номер - порт в контейнере
